export const ddpTerritories = [
    "Dalal Street",
    "Bandra-Kurla Complex",
    "Connaught Place",
    "Nehru Place",
    "HITEC City",
    "Electronics City",
    "CyberHub",
    "Salt Lake Sector V",
    "GIFT City",
    "T. Nagar",
    "Chandni Chowk",
    "Crawford Market",
    "Burrabazar",
    "KR Market",
    "Laad Bazaar",
    "Sadar Bazaar",
    "Azadpur Mandi",
    "Zaveri Bazaar",
    "Surat Textile Market",
    "Gandhi Market",
    "APMC Navi Mumbai",
    "Rajkot Gold Market",
    "Vashi Market",
    "Meena Bazaar",
    "Johari Bazaar",
    "Manek Chowk",
    "Chickpet Market",
    "Dadar Flower Market",
    "Mullick Ghat Flower Market",
    "Koyambedu Market",
    "Phoenix Marketcity",
    "Lulu Mall (Kochi)",
    "Lulu Mall (Lucknow)",
    "Saravana Stores",
    "Brigade Road",
    "MG Road (Pune)",
    "Select Citywalk",
    "Ambience Mall",
    "DLF Mall of India",
    "Orion Mall",
    "Palika Bazaar",
    "New Market",
    "Hazratganj",
    "Abids",
    "Commercial Street",
    "Pondy Bazaar",
    "Law Garden",
    "Dilli Haat",
    "Janpath Market",
    "Sarojini Nagar"
];
