export const mfTerritories = [
    "Delhi NCR",
    "Telangana",
    "Odisha",
    "Rajasthan",
    "Western Madhya Pradesh",
    "Eastern Madhya Pradesh",
    "Mumbai Metropolitan & Western Maharashtra",
    "Central & South Gujarat",
    "North Gujarat & Saurashtra",
    "Western & Central Uttar Pradesh",
    "Andhra Pradesh",
    "South & Urban Karnataka",
    "Chennai & Northern Tamil Nadu",
    "North & Central Karnataka",
    "Haryana",
    "Southern & Western Tamil Nadu",
    "West Bengal",
    "Marathwada & Southern Maharashtra",
    "Vidarbha & North Maharashtra",
    "Eastern Uttar Pradesh & Bundelkhand",
    "Chhattisgarh",
    "Goa",
    "Himachal Pradesh",
    "Jammu & Kashmir",
    "North East",
    "Uttarakhand",
    "Jharkhand",
    "Punjab",
    "Bihar",
    "Kerala"
];
